config/routes.rb
Rails.application.routes.draw do
  resources :wine_types

  resources :user_wines

  resources :stages

  resources :wines

  resources :varietals

  resources :appellations

  resources :vineyards

  get 'pages/search'

  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/user_wine.rb
class UserWine < ActiveRecord::Base
  belongs_to :user
  belongs_to :wine
  belongs_to :stage
end

app/controllers/user_wines_controller.rb
class UserWinesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user_wine, only: [:show, :edit, :update, :destroy]

  # GET /user_wines
  # GET /user_wines.json
  def index
    @user_wines = UserWine.all
  end

  # GET /user_wines/1
  # GET /user_wines/1.json
  def show
  end

  # GET /user_wines/new
  def new
    @user_wine = UserWine.new
  end

  # GET /user_wines/1/edit
  def edit
  end

  # POST /user_wines
  # POST /user_wines.json
  def create
    @user_wine = UserWine.new(user_wine_params)

    respond_to do |format|
      if @user_wine.save
        format.html { redirect_to @user_wine, notice: 'User wine was successfully created.' }
        format.json { render :show, status: :created, location: @user_wine }
      else
        format.html { render :new }
        format.json { render json: @user_wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_wines/1
  # PATCH/PUT /user_wines/1.json
  def update
    respond_to do |format|
      if @user_wine.update(user_wine_params)
        format.html { redirect_to @user_wine, notice: 'User wine was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_wine }
      else
        format.html { render :edit }
        format.json { render json: @user_wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_wines/1
  # DELETE /user_wines/1.json
  def destroy
    @user_wine.destroy
    respond_to do |format|
      format.html { redirect_to user_wines_url, notice: 'User wine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_wine
      @user_wine = UserWine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_wine_params
      params.require(:user_wine).permit(:user_id, :wine_id, :stage_id, :rating, :review)
    end
end

app/helpers/user_wines_helper.rb
module UserWinesHelper
end

app/views/user_wines/_form.html.erb
<%= simple_form_for(@user_wine) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :user %>
    <%= f.association :wine %>
    <%= f.association :stage %>
    <%= f.input :rating %>
    <%= f.input :review %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/user_wines/edit.html.erb
<h1>Editing User Wine</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_wine %> |
<%= link_to 'Back', user_wines_path %>

app/views/user_wines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Wines</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Wine</th>
      <th>Stage</th>
      <th>Rating</th>
      <th>Review</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_wines.each do |user_wine| %>
      <tr>
        <td><%= user_wine.user %></td>
        <td><%= user_wine.wine %></td>
        <td><%= user_wine.stage %></td>
        <td><%= user_wine.rating %></td>
        <td><%= user_wine.review %></td>
        <td><%= link_to 'Show', user_wine %></td>
        <td><%= link_to 'Edit', edit_user_wine_path(user_wine) %></td>
        <td><%= link_to 'Destroy', user_wine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User wine', new_user_wine_path %>

app/views/user_wines/new.html.erb
<h1>New User Wine</h1>

<%= render 'form' %>

<%= link_to 'Back', user_wines_path %>

app/views/user_wines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_wine.user %>
</p>

<p>
  <strong>Wine:</strong>
  <%= @user_wine.wine %>
</p>

<p>
  <strong>Stage:</strong>
  <%= @user_wine.stage %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @user_wine.rating %>
</p>

<p>
  <strong>Review:</strong>
  <%= @user_wine.review %>
</p>

<%= link_to 'Edit', edit_user_wine_path(@user_wine) %> |
<%= link_to 'Back', user_wines_path %>