config/routes.rb
Rails.application.routes.draw do
  resources :wine_types

  resources :user_wines

  resources :stages

  resources :wines

  resources :varietals

  resources :appellations

  resources :vineyards

  get 'pages/search'

  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/appellation.rb
class Appellation < ActiveRecord::Base
  has_many :wines
end

app/controllers/appellations_controller.rb
class AppellationsController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only
  before_action :set_appellation, only: [:show, :edit, :update, :destroy]

  # GET /appellations
  # GET /appellations.json
  def index
    @appellations = Appellation.all
  end

  # GET /appellations/1
  # GET /appellations/1.json
  def show
  end

  # GET /appellations/new
  def new
    @appellation = Appellation.new
  end

  # GET /appellations/1/edit
  def edit
  end

  # POST /appellations
  # POST /appellations.json
  def create
    @appellation = Appellation.new(appellation_params)

    respond_to do |format|
      if @appellation.save
        format.html { redirect_to @appellation, notice: 'Appellation was successfully created.' }
        format.json { render :show, status: :created, location: @appellation }
      else
        format.html { render :new }
        format.json { render json: @appellation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appellations/1
  # PATCH/PUT /appellations/1.json
  def update
    respond_to do |format|
      if @appellation.update(appellation_params)
        format.html { redirect_to @appellation, notice: 'Appellation was successfully updated.' }
        format.json { render :show, status: :ok, location: @appellation }
      else
        format.html { render :edit }
        format.json { render json: @appellation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appellations/1
  # DELETE /appellations/1.json
  def destroy
    @appellation.destroy
    respond_to do |format|
      format.html { redirect_to appellations_url, notice: 'Appellation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def admin_only
    unless current_user.admin?
      redirect_to root_path, :alert => "Access denied."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appellation
      @appellation = Appellation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appellation_params
      params.require(:appellation).permit(:app_name, :app_region, :app_area)
    end
end

app/helpers/appellations_helper.rb
module AppellationsHelper
end

app/views/appellations/_form.html.erb
<%= simple_form_for(@appellation) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :app_name %>
    <%= f.input :app_region %>
    <%= f.input :app_area %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/appellations/edit.html.erb
<h1>Editing Appellation</h1>

<%= render 'form' %>

<%= link_to 'Show', @appellation %> |
<%= link_to 'Back', appellations_path %>

app/views/appellations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Appellations</h1>

<table>
  <thead>
    <tr>
      <th>App name</th>
      <th>App region</th>
      <th>App area</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appellations.each do |appellation| %>
      <tr>
        <td><%= appellation.app_name %></td>
        <td><%= appellation.app_region %></td>
        <td><%= appellation.app_area %></td>
        <td><%= link_to 'Show', appellation %></td>
        <td><%= link_to 'Edit', edit_appellation_path(appellation) %></td>
        <td><%= link_to 'Destroy', appellation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appellation', new_appellation_path %>

app/views/appellations/new.html.erb
<h1>New Appellation</h1>

<%= render 'form' %>

<%= link_to 'Back', appellations_path %>

app/views/appellations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>App name:</strong>
  <%= @appellation.app_name %>
</p>

<p>
  <strong>App region:</strong>
  <%= @appellation.app_region %>
</p>

<p>
  <strong>App area:</strong>
  <%= @appellation.app_area %>
</p>

<%= link_to 'Edit', edit_appellation_path(@appellation) %> |
<%= link_to 'Back', appellations_path %>