config/routes.rb
Rails.application.routes.draw do
  resources :wine_types

  resources :user_wines

  resources :stages

  resources :wines

  resources :varietals

  resources :appellations

  resources :vineyards

  get 'pages/search'

  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/appellation.rb
class Appellation < ActiveRecord::Base
  has_many :wines
end

app/models/stage.rb
class Stage < ActiveRecord::Base
  has_many :user_wines
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_wines

  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_wine.rb
class UserWine < ActiveRecord::Base
  belongs_to :user
  belongs_to :wine
  belongs_to :stage
end

app/models/varietal.rb
class Varietal < ActiveRecord::Base
  belongs_to :wine_type
  has_many :wines
end

app/models/vineyard.rb
class Vineyard < ActiveRecord::Base
  has_many :wines
end

app/models/wine.rb
class Wine < ActiveRecord::Base
  belongs_to :vineyard
  belongs_to :appellation
  belongs_to :varietal

  has_many :user_wines
end

app/models/wine_type.rb
class WineType < ActiveRecord::Base
  has_many :varietals
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:search]

  def search
    # http://ruby-doc.org/stdlib-2.0.0/libdoc/open-uri/rdoc/OpenURI.html
    require 'open-uri'

  if params[:search]
    # Construct the URL we'll be calling
    request_uri = 'http://services.wine.com/api/beta2/service.svc/json/catalog?apikey=c880d81f0c6e496f2605bead17ddd36c'
    request_type = '&size=10&type="wine"&search='
    request_query = "#{params[:search]}"
    url = "#{request_uri}#{request_type}'#{request_query}'"

    # Actually fetch the contents of the remote URL as a String.
    encoded_url = URI.encode(url)
    buffer = URI.parse(encoded_url).read

    # Convert the String response into a plain old Ruby array. It is faster and saves you time compared to the standard Ruby libraries too.
    @result = JSON.parse(buffer)
    @raw_products = @result["Products"]["List"]
    @products = Array.new

    @raw_products.each do |wine|
      # Filter out other products
      if wine["Type"] == "Wine"
        new_wine = Hash.new
        new_wine["label"] = wine["Labels"][0]["Url"]
        new_wine["name"] = wine["Name"]
        new_wine["vineyard"] = wine["Vineyard"]["Name"]
        new_wine["url"] = wine["Url"]
        new_wine["appellation_region"] = wine["Appellation"]["Region"]["Name"]
        new_wine["appellation_name"] = wine["Appellation"]["Name"]
        new_wine["varietal_type"] = wine["Varietal"]["WineType"]["Name"]
        new_wine["varietal_name"] = wine["Varietal"]["Name"]
        new_wine["pricemin"] = wine["PriceMin"]
        new_wine["pricemax"] = wine["PriceMax"]
        new_wine["attributes"] = Array.new
        wine["ProductAttributes"].each do |attribute|
          new_wine["attributes"] << attribute["Name"]
        end
        @products << new_wine
      end
    end

    #TODO:  figure out how to grab the thumbnail or larger image, not the first image.
  else
    @products
  end


  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :admin_only, :except => :show

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to root_path, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :admin_only
  before_action :set_wine, only: [:show, :edit, :update, :destroy]

  # GET /wines
  # GET /wines.json
  def index
    @wines = Wine.all
  end

  # GET /wines/1
  # GET /wines/1.json
  def show
  end

  # GET /wines/new
  def new
    @wine = Wine.new
  end

  # GET /wines/1/edit
  def edit
  end

  # POST /wines
  # POST /wines.json
  def create
    @wine = Wine.new(wine_params)

    respond_to do |format|
      if @wine.save
        format.html { redirect_to @wine, notice: 'Wine was successfully created.' }
        format.json { render :show, status: :created, location: @wine }
      else
        format.html { render :new }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wines/1
  # PATCH/PUT /wines/1.json
  def update
    respond_to do |format|
      if @wine.update(wine_params)
        format.html { redirect_to @wine, notice: 'Wine was successfully updated.' }
        format.json { render :show, status: :ok, location: @wine }
      else
        format.html { render :edit }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wines/1
  # DELETE /wines/1.json
  def destroy
    @wine.destroy
    respond_to do |format|
      format.html { redirect_to wines_url, notice: 'Wine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def admin_only
    unless current_user.admin?
      redirect_to root_path, :alert => "Access denied."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wine
      @wine = Wine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wine_params
      params.require(:wine).permit(:vineyard_id, :appellation_id, :varietal_id, :name, :label_url, :api_url, :pricemin, :pricemax, :attributes, :sku, :api_provider, :api_id)
    end
end

app/helpers/appellations_helper.rb
module AppellationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/stages_helper.rb
module StagesHelper
end

app/helpers/user_wines_helper.rb
module UserWinesHelper
end

app/helpers/varietals_helper.rb
module VarietalsHelper
end

app/helpers/vineyards_helper.rb
module VineyardsHelper
end

app/helpers/wine_types_helper.rb
module WineTypesHelper
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
<% if user_signed_in? %>
  <li><%= link_to 'My wines', user_wines_path %></li>
  <li><%= link_to 'Search wines', pages_search_path %></li>
  <% if current_user.admin? %>
    <li><%= link_to 'Stages', stages_path %></li>
    <li><%= link_to 'Varietals', varietals_path %></li>
    <li><%= link_to 'Appellations', appellations_path %></li>
    <li><%= link_to 'Vineyards', vineyards_path %></li>
    <li><%= link_to 'Wines', wines_path %></li>
  <% end %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Oinos" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Oinos" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <div class="container">
      <main role="main">
         <%= render 'layouts/messages' %>
         <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/pages/search.html.erb
<h1>Search for Wine</h1>
<h2>Products:</h2>

<%= form_tag(pages_search_path, :method => "get", id: "search-form", class: "form-inline") do %>
  <div class="form-group">
    <%= text_field_tag :search, params[:search], :class => "form-control", placeholder: "Search Wines" %>
    <%= submit_tag "Search", :request_query => nil, :class => "btn btn-default" %>
  </div>
<% end %>

<div id="attribution">
  Search provided by
  <a href="http://www.wine.com/" title="Wine.com the destination for Wine and Wine Gifts"><img src="http://cache.wine.com/images/logos/80x20_winecom_logo.png" alt="Wine.com the destination for Wine and Wine Gifts" /></a>
</div>

<% if @products != nil %>
  <% @products.each do |wine| %>
    <%= form_tag(new_user_wine_path, :method => "get", class: "form-inline") do %>
      <div class="form-group">
        <%= image_tag(wine["label"]) %><br>
        <b><%= wine["name"] %></b> by <%= wine["vineyard"] %><br>
        <%= wine["url"] %><br>
        Appellation:  <%= wine["appellation_name"] %>, <%= wine["appellation_region"] %><br>
        Varietal:  <%= wine["varietal_name"] %><br>
        <% if wine["pricemin"] != nil %>
          Price range:  $<%= wine["pricemin"] %> - $<%= wine["pricemax"] %><br>
        <% end %>
        <% if wine["attributes"].length > 0 %>
          Attributes:<br>
          <ul>
            <% wine["attributes"].each do |attribute| %>
              <li><%= raw(attribute) %></li>
            <% end %>
          </ul>
        <% end %>
        <%= button_to 'Add to Wines', user_wines_path(wine_id: wine) %>
        <%= button_to 'Add to My Wines', user_wines_path(wine_id: wine) %>
      </div>
    <% end %>
    <br>
  <% end %>
<% else %>
  <br>
  No results.
<% end %>